name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'
  - title: '🔄 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'

autolabeler:
  - label: 'feature'
    title:
      - '/^feat(ure)?(\(.+\))?[:/]/i'
    branch:
      - '/^feat(ure)?\//'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?[:/]/i'
    branch:
      - '/^fix\//'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?[:/]/i'
      - '/^refactor(\(.+\))?[:/]/i'
    branch:
      - '/^chore\//'
      - '/^refactor\//'
  - label: 'documentation'
    title:
      - '/^docs?(\(.+\))?[:/]/i'
    branch:
      - '/^docs?\//'
  - label: 'performance'
    title:
      - '/^perf(ormance)?(\(.+\))?[:/]/i'
    branch:
      - '/^perf(ormance)?\//'
  - label: 'dependencies'
    branch:
      - '/^renovate\//'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
  default: patch

template: |
  ## Changes

  $CHANGES
  
  ## Docker
  ```
  docker pull lakker/pulsarr:$RESOLVED_VERSION
  ```

  **Synology NAS / Legacy Systems** (Linux kernel < 4.11):
  ```
  docker pull lakker/pulsarr:$RESOLVED_VERSION-node
  ```

  ## Contributors
  
  $CONTRIBUTORS