name: Discord Release Notifications (Stable)

on:
  release:
    types: [published]  # Stable releases only

permissions:
  contents: read

jobs:
  github-releases-to-discord:
    if: ${{ !github.event.release.draft && !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@b96a33520f8ad5e6dcdecee6f1212bdf88b16550 # v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "4760230"
          username: "Pulsarr Releases"
          avatar_url: "https://raw.githubusercontent.com/jamcalli/Pulsarr/master/assets/icons/pulsarr-lg.png"
          content: "🚀 New Pulsarr release is available! ||@everyone||"
          footer_title: "Pulsarr"
          footer_timestamp: true
          reduce_headings: true
