name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-drafting
  queue: max

jobs:
  draft:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  autolabel:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter/autolabeler@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
