name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafting

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7
