name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafting
  queue: max

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7
